### ISSUE TITLE
Broken Links im Footer Version 1.5

### ISSUE THREAD

**Issue by ghost** [Schulconnex/Schulconnex#180]
Broken Links im Footer Menu von Version 1.5.

Beispiel-URL: https://schulconnex.github.io/Schulconnex/docs/footer/impressum (broken)
Erwartete URL: https://schulconnex.github.io/Schulconnex/docs/1.5/footer/impressum

Siehe Docusaurus Issue: https://github.com/facebook/docusaurus/issues/7402
Workaround: https://github.com/tauri-apps/tauri-docs/issues/589

Betrifft: https://github.com/Schulconnex/Schulconnex/blob/main/docusaurus.config.ts
Vorschlag Quick Fix: hier vorerst fest '/docs/1.5/' im Pfad eintragen (funktioniert, so lange wir nur eine Version ausspielen).

```yaml
footer: {
        style: 'dark',
        links: [
          {
            title: 'Schulconnex',
            items: [
              {
                label: 'Einleitung',
                to: '/docs/einleitung',
              },
              {
                label: 'Allgemeines',
                to: '/docs/allgemeines',
              },
            ],
          }
```

<img width="387" alt="footer_menu" src="https://github.com/user-attachments/assets/48e2f484-f90f-4901-9847-18cae1983eb5">
