### ISSUE TITLE
example UUID for &ref_20 ist nicht korrekt

### ISSUE THREAD

**Issue by chrisburkh** [Schulconnex/Schulconnex#212]
```
                    properties: &ref_20
                      id:
                        description: ID der Sichtfreigabe.
                        type: string
                        format: uuid
                        example: 488dfea40-5fe9-427e-a92f-811af17d022c
```

Die Beispiel UUID ist keine valide UUID.
