### ISSUE TITLE
Pfad Parameter für GET /personenkontexte/{id}/sichtfreigaben sollte als required markiert werden

### ISSUE THREAD

**Issue by chrisburkh** [Schulconnex/Schulconnex#213]
```
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          description: Der Pfad-Parameter bezieht sich auf die ID des Personenkontextes.
```

Hier sollte der Parameter als 
```
          required: true
```
gesetzt werden.
